# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# Npm publish options
before_deploy:
  - export TRAVIS_BUILD_PASSED=true
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: X+57oXFXkP9rVq/llYkof7nuYuBX6OJPwMwL60bxHerr0LAzIPy4HAZi6HqIJwYXPuhAXPk9jkYj93cPu98kPAOXIcCFSWLEnv3/SB/3aKCyn0Bn2Ei7igjU+LB0L8KQ36dsqVMuCvISQiUU/MuqqhCN/0OZuKIbOyRQMf7NwaTBKkBDsX7XCTXMSdT3d06djfIEs1L12MYgtoh9btiF8v8zUyBITxuf22iI9g7M4O1Uk4A17N1UD6qTsFzeCJhHVgL2gHluKgzA2zdoWy22A88LkK1u2TOl+49VSoxVaGCbV9xZ9rjbLoiCBr9bTy6/soooCrOPz6BIipCtk4ea7+o1hUVDuBkqyIkXLF3kAflPDoXmJVKTb96HLyM9qm/zAV+SX5I90jG4QL+cV8mpvyIprsVTPQ13tb2xd804V5KVdE9CnL8sZA6AMxame0nuT/6ktI3P6yAp6u4MxC01FZ9Pxt75QZYvibeGYbN/quVjmo5ta03BB97ciNghjYqgMWbF7LTnmHXqLtCAiUPd34BKEeak0Cxw7F66gZjTvcgvn8VkRAOZXWVPRufYDAbArCtg/+rysx1o/SSCTfPV/kthSodZtuAAPft7nUk7qhzvAaaj6VR6fEdgsld6TYwfbqZrdrBzUdd87tSZpDN0ToMFSoX5qtNhjXLFO/kcBGM=

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: exQPydAMNRBWp8/KbcAVjoMukyT1wmPhiLVUMtuT5Q8zeN7kziAl7PjtuTgL4oxVwljn1cxlSlHpN+qR66daIfCjzHJwUpgKElUpFl8Y+SiI/fXiYNMVedyrubJkdmRzfmuwdIYbVW1jt+2dbnQEEO/hT3HpYpUIKwYCN9SQWRtAZAtwz6cYWu1jY8tesu/41aeOT+sn2Zqy/Z+j6SIXGPOm8vBYeKRTJ2uCPvONPvxAagqC9BirTePX0I9TLexihIIJgE2iSD7NaTXv76DuVbeUt69wEfEmC0TuNsLDd+r6TFytrs9iXXqN65kmA3g7yHx6s0EYpxvqniT0EcZ2M9Tztj2F99a5WVWQJw8QQ8MUtdmjOvsughTQ2QHIDC97UAWyHYmCluE7Qo94z9T3Tfpduth/fbKXMWZTYiZMJenNZsSsez91m8XUJneGu5w9J+ZsqMfjk0EYDi9qI2fwZk54CRk7d0/8jPlryU52/cf2Y7e51A//NX4Lv6di7Bz+orql31NbIVBcbrjpMvhhXXxG1yEP/pgJ6h91w22eiJcsbSZur7iXQEG/KoDmsknkxX+hUAYL0byTqtw2I3zfqZvfxUX3HcL2WxfPjAVmk1QCrYv/p5mTwzV/oizZCj4/pkDr4Tc2gpDYP2OMwU5yL6F345H4gdOUHokJVG49Y0I=
    # SAUCE_TOKENS
    - secure: m9BMEAR49UjfnSITCWkW0b6RsJ6TwP+EexDNJaEeSZsODOzYK6zR1JKQBVgF5JhSnuZjkXBmncdax1LirADhEw504Bl3a/zMlxQm+GpwTcMHikZQCXTRUtZOKCq31AM8pufAK/9fGFPAdUtgt4takc0RaBrS/tFbDKGOsUy+3H/ymZSI2BGBlrKZD+gaZzlX9dnEY2EwwJKHdFvnjf14eVab1DUXav0I9+C3873YgCfLtTf+/Rzb9SeSuCK6jZq3sHffDIfYWtYo5cgNcNBiEmDGGeLDZ/nHDDj2gmcOsO4yjhEvluFg8cOzQMb+5jhxBYL11nBiEU+zvfaVHssZrDIlPYearhE87w3lN3oXoSqpHqzsFu3WssRsl/j0OvDVmF8eHKSOdPz2ZOhlmiV2ZUrszP17+ocS5c22gTAP/mHUNlCsSOFaZNioV2EQ2ljJkM2q+aoEIbTN1Y/99StsJ1gcVpVReZl5PGCsq+R8J6eXrbTwvC86hAM4/uEStIlKJzIYpvQasgNDa4VLEw9DXECWFRZ1xZfaKf4dnGlLrxh1EcWmBPOmVEsWWaFRhCC6THTB6Rpchekcmh/L8WH9Rxw52ctsiliDG84KS/PjMlPCqc5mPhtreghvJatBPT+rKwyU54k83oouqWkfMVtJewVmT4jtw89a7sVwgTH6dfk=
    - secure: T1JCtjz7KiSVjL/HJ6t1MShL7J43E2bEp6Mq9ki/0K9ZUUBVfSwyPdDu5sxl0oaW27UmYajq/bp3v+C3gdjkFkO35Te4iKyyC8lVL86IvXvIzDlAMP3ILY6VaaaBKVyGx8iWSTWE+oL3wx2Z7Jed1kw96HeJUrWQhC5KWiV1Ar0imq0jreoBd7+3SgIcKCq/UJmSEHea2HP2DTlPexr/CE1Dp9nYzgJa2goHLidlUCgo6WE9b72EbjqW77ww0RNUAbcdS4+DuCEoSo/6kTO5akQD5pJGNFjtQUfNzrM9ZaJLJzPmP6sr9pbL4FOeIpreVvAON4mfuExlYfVj78vssO8TfXAYXvBwKXRz9h0epjnTTup+39g5dig+3Spwvnvy9XHoQ1ySucEBHLLp/64vlf9itXEqiPcNRPqXysLRbZh1E3g3aXOgXOrU437kF/92LuT4pSfWJa6z+j+HsjHQhlS7pFM3l8xYOwl5v/Dc72GowZLO8bLbIvkg7UooZm8TOCpbZlFTMJWgMKkOae+19E6sKsqbe2SBVx/09raKa2DYhVNct12BfrNG6Nal10He4U2pvvmlNykWdV4P0kgVe7WUNNtNV1hyrDTsdQPxPBzw5kWMR4S0PJ+73IwzCry8w7iQ9yUh1wyeflFTwjUwlRt1AjOYu1f7b3Q62bzYEb4=
